name: Build and Deploy Spring app

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/aws-spring-demo:latest .
      - name: Login to Docker-hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Publish image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/aws-spring-demo:latest

  deploy:
    needs: build
    name: Deploy to ec2
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/aws-spring-demo:latest
      - name: Delete old container
        run: docker rm -f aws-demo-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name aws-demo-container ${{ secrets.DOCKER_HUB_USERNAME }}/aws-spring-demo:latest